AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets for K-Seat

Resources:

  EventPictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: k-seat-event-picture
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PlaceLayoutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: k-seat-place-layout
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  PlacePictureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: k-seat-place-picture
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true